Rework branch backend
mihaihosu/NessLabs pull request #10
Opened 2023-05-12 17:25 UTC by alexbhr13

2023-05-16 06:25 UTC, VoicuVL requested changes

2023-05-16 06:25 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/controller/RegistrationController.java
>  @AllArgsConstructor
@RequiredArgsConstructor

2023-05-16 06:25 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +@AllArgsConstructor
la fel ca mai sus

2023-05-16 06:25 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +    private PasswordValidatorService passwordValidatorService;
tot final poti

2023-05-16 06:25 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserDetailsService, UserService{
la fel

2023-05-16 06:25 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/UserServiceImpl.java
> +    @Override
daca ai override trebuie pus si in interfata ca sa stii la ce faci override

2023-05-16 15:15 UTC, slgnalin approved these changes

2023-05-17 07:11 UTC, slgnalin requested changes

2023-05-17 07:11 UTC, slgnalin commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +        if (request.getUsername().isEmpty() || request.getUsername() == null) {
Do we need both `isEmpty` and `== null` checks? It seems like the second one is redundant.
I believe that the implementation of `isEmpty()` performs a null check, verifies whether the provided String is empty or only contains whitespaces
Please have a look and remove any check that is redundant, or let me know if this is not the case

2023-05-17 10:10 UTC, SuperxJoker commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +        if (request.getUsername().isEmpty() || request.getUsername() == null) {
I've searched and says that  if is null, attempting to call .isEmpty() will throw a null pointer exception, so both not necessary.

2023-05-18 07:12 UTC, VoicuVL requested changes

2023-05-18 07:12 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +    public User register(RegistrationRequest request) throws InvalidCredentialException {
@Override

2023-05-19 09:35 UTC, VoicuVL approved these changes

2023-05-23 17:50 UTC, slgnalin commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +        if (request.getUsername().isEmpty() || request.getUsername() == null) {
Then, I believe the Null Pointer Exception will be thrown regardles, as it will first perform the `request.getUsername().isEmpty()` check. If this passes, `== null` is redundant.
Is there a `isNullOrEmpty()` method that check for both `null` or `empty` values? If yes, that should be used here.
If not, then we should first perform the `null` check and only if the username is NOT null, perform the `isEmpty` check.
If what I meant is not clear, feel free to send me a message on Discord. It's harder for me to follow the conversations here

2023-05-23 17:52 UTC, slgnalin requested changes
See my comment here https://github.com/mihaihosu/NessLabs/pull/10/files#diff-6db0e15d9df1a2fabf5324df99cd78b755400d9f7490e3e50d1a76996e91fba8R27

2023-05-23 17:52 UTC, slgnalin commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/RegistrationServiceImpl.java
> +        if (request.getUsername().isEmpty()) {
If `.isEmpty()` can throw an NPE, then we should also perform a NULL check. 
Please see the method implementation and investigate whether this is required or not

2023-05-24 12:00 UTC, slgnalin approved these changes

2023-05-24 12:24 UTC, merged