26 user creation backend
mihaihosu/NessLabs pull request #4
Opened 2023-05-04 09:39 UTC by AnaMaghear

2023-05-05 10:39 UTC, VoicuVL requested changes
Good job

2023-05-05 10:39 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/config/ApplicationConfig.java
cred ca vei folosi asta din branchul Alexiei

2023-05-05 10:39 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/config/SecurityConfiguration.java
la fel

2023-05-05 10:39 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/controller/RegistrationController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
poti sa pui codul la fel ca mai jos, adica HTTPSTATUS.BADREQUEST sau mai jos sa pui .ok() ca sa fie la fel facut

2023-05-05 10:39 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/model/User.java
> +    private String username;
vorbiti daca mai aveti nevoie de username

2023-05-05 10:39 UTC, VoicuVL commented on ness-lab-spring/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
sa pui update

2023-05-05 10:39 UTC, VoicuVL commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/UserService.java
> +        userRepository.save(user);
poti folosi saveAndFlush

citeste despre diferente

2023-05-07 08:00 UTC, AnaMaghear commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/service/UserService.java
> +        userRepository.save(user);
✅

2023-05-07 08:00 UTC, AnaMaghear commented on ness-lab-spring/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
✅

2023-05-07 08:01 UTC, AnaMaghear commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/model/User.java
> +    private String username;
S-a decis sa ramana ambele (username si email)

2023-05-07 08:01 UTC, AnaMaghear commented on ness-lab-spring/src/main/java/com/nesslabs/nesslabspring/controller/RegistrationController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
✅

2023-05-08 11:38 UTC, VoicuVL approved these changes

2023-05-08 17:35 UTC, merged